export company="ascap"
export project="cue2"
export app_name="data-migration"
export region="us-east-1"
export image="data-migration"
#export auto_decline="auto-decline"
#export sales_force="sales-force"
